version: '3'
services:
  myapp:
    build: .
    ports:
     - "9001:9001"
    environment:
      - MSG_SERV=messageapp
      - PORT=3000
      - CLIENT_PORT=9001
  messageapp:
    image: "cabify/backend-bootcamp-messageapp:latest"
    ports:
      - "3000:3000"

  